### ISSUE TITLE
Reason: dllctypes_stubs.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by djs55** [simonjbeaumont/ocaml-pci#16]
When building under CentOS 7 with https://github.com/djs55/xenserver-core/blob/toolstack-updates/SPECS/ocaml-pci.spec I get:

```
Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.93vQnW
+ umask 022
+ cd /builddir/build/BUILD
+ LANG=C
+ export LANG
+ unset DISPLAY
+ cd /builddir/build/BUILD
+ rm -rf ocaml-pci-0.2.0
+ /usr/bin/gzip -dc /builddir/build/SOURCES/ocaml-pci-0.2.0.tar.gz
+ /bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd ocaml-pci-0.2.0
+ /bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.lfj3Zf
+ umask 022
+ cd /builddir/build/BUILD
+ cd ocaml-pci-0.2.0
+ LANG=C
+ export LANG
+ unset DISPLAY
+ ./configure
Configuration:
ocamlfind: ........................................... /usr/bin/ocamlfind
ocamlc: .............................................. /usr/bin/ocamlc.opt
ocamlopt: ............................................ /usr/bin/ocamlopt.opt
ocamlbuild: .......................................... /usr/bin/ocamlbuild
Package name: ........................................ pci
Package version: ..................................... 0.2.0
os_type: ............................................. Unix
system: .............................................. linux
architecture: ........................................ amd64
ccomp_type: .......................................... cc
ocaml_version: ....................................... 4.01.0
standard_library_default: ............................ /usr/lib64/ocaml
standard_library: .................................... /usr/lib64/ocaml
standard_runtime: .................................... /usr/bin/ocamlrun
bytecomp_c_compiler: ................................. gcc -fno-defer-pop -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -O2 -g -fPIC
native_c_compiler: ................................... gcc -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -O2 -g
model: ............................................... default
ext_obj: ............................................. .o
ext_asm: ............................................. .s
ext_lib: ............................................. .a
ext_dll: ............................................. .so
default_executable_name: ............................. a.out
systhread_supported: ................................. true
Install architecture-independent files dir: .......... /usr/local
Install architecture-dependent files in dir: ......... $prefix
User executables: .................................... $exec_prefix/bin
System admin executables: ............................ $exec_prefix/sbin
Program executables: ................................. $exec_prefix/libexec
Read-only single-machine data: ....................... $prefix/etc
Modifiable architecture-independent data: ............ $prefix/com
Modifiable single-machine data: ...................... $prefix/var
Object code libraries: ............................... $exec_prefix/lib
Read-only arch-independent data root: ................ $prefix/share
Read-only architecture-independent data: ............. $datarootdir
Info documentation: .................................. $datarootdir/info
Locale-dependent data: ............................... $datarootdir/locale
Man documentation: ................................... $datarootdir/man
Documentation root: .................................. $datarootdir/doc/$pkg_name
HTML documentation: .................................. $docdir
DVI documentation: ................................... $docdir
PDF documentation: ................................... $docdir
PS documentation: .................................... $docdir
findlib_version: ..................................... 1.5.5
is_native: ........................................... true
suffix_program: ......................................
Remove a file.: ...................................... rm -f
Remove a directory.: ................................. rm -rf
Turn ocaml debug flag on: ............................ true
Turn ocaml profile flag on: .......................... false
Compiler support generation of .cmxs.: ............... true
OCamlbuild additional flags: .........................
Compile example executables: ......................... false
Create documentations: ............................... true
Compile tests executable and library and run them: ... false
pkg_ctypes_stubs: .................................... /usr/lib64/ocaml/ctypes
ocaml setup.ml -build
+ make
W: Cannot find source file matching module 'Ffi_generated' in library pci
W: Cannot find source file matching module 'Ffi_generated_types' in library pci
/usr/bin/ocamlopt.opt unix.cmxa -I /usr/lib64/ocaml/ocamlbuild /usr/lib64/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /usr/lib64/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
/usr/bin/ocamlfind ocamldep -package ctypes.stubs -modules bindings/ffi_bindings.ml > bindings/ffi_bindings.ml.depends
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package ctypes.stubs -I bindings -o bindings/ffi_bindings.cmo bindings/ffi_bindings.ml
/usr/bin/ocamlfind ocamlc -a bindings/ffi_bindings.cmo -o bindings/pci_bindings.cma
/usr/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -package ctypes.stubs -I bindings -o bindings/ffi_bindings.cmx bindings/ffi_bindings.ml
/usr/bin/ocamlfind ocamlopt -a bindings/ffi_bindings.cmx -o bindings/pci_bindings.cmxa
/usr/bin/ocamlfind ocamlopt -shared bindings/pci_bindings.cmxa bindings/ffi_bindings.cmx -o bindings/pci_bindings.cmxs
/usr/bin/ocamlfind ocamldep -package ctypes.stubs -modules stubgen/ffi_stubgen.ml > stubgen/ffi_stubgen.ml.depends
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I bindings -package ctypes.stubs -I stubgen -I bindings -o stubgen/ffi_stubgen.cmo stubgen/ffi_stubgen.ml
/usr/bin/ocamlfind ocamlc -g -linkpkg -package ctypes.stubs bindings/pci_bindings.cma stubgen/ffi_stubgen.cmo -o stubgen/ffi_stubgen.byte
stubgen/ffi_stubgen.byte -c > lib/ffi_generated_stubs.c
+ stubgen/ffi_stubgen.byte -c > lib/ffi_generated_stubs.c
Fatal error: cannot load shared library dllctypes_stubs
Reason: dllctypes_stubs.so: cannot open shared object file: No such file or directory
Command exited with code 2.
E: Failure("Command ''/usr/bin/ocamlbuild' bindings/pci_bindings.cma bindings/pci_bindings.cmxa bindings/pci_bindings.a bindings/pci_bindings.cmxs lib/libpci_stubs.a lib/dllpci_stubs.so lib/pci.cma lib/pci.cmxa lib/pci.a lib/pci.cmxs stubgen/ffi_stubgen.byte stubgen/ffi_types_stubgen.byte -tag debug' terminated with error code 10")
make: *** [build] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.lfj3Zf (%build)
    Bad exit status from /var/tmp/rpm-tmp.lfj3Zf (%build)
RPM build errors:
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/ocaml-pci.spec
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 493, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/ocaml-pci.spec
LEAVE do --> EXCEPTION RAISED
```

**Comment by simonjbeaumont** [comment]
This is a bug with the `ocaml-ctypes` spec file. You should apply the following patch (taken from my commit to xen-dist-ocaml.hg):

```
[ssh:simonbe@morbo SPECS] hg export 169:ed25d30da140
# HG changeset patch
# User Si Beaumont <simon.beaumont@citrix.com>
# Date 1430503318 -3600
#      Fri May 01 19:01:58 2015 +0100
# Node ID ed25d30da14099fdc4c9720d96a9cc1cf6ac7430
# Parent  b51cbb636ce59faf5755996da45f283aad192e56
Fixup ocaml-ctypes packaging

diff --git a/SPECS/ocaml-ctypes.spec b/SPECS/ocaml-ctypes.spec
--- a/SPECS/ocaml-ctypes.spec
+++ b/SPECS/ocaml-ctypes.spec
@@ -1,6 +1,6 @@
 Name:           ocaml-ctypes
 Version:        0.4.1
-Release:        1%{?dist}
+Release:        2%{?dist}
 Summary:        Library for binding to C libraries using pure OCaml
 License:        MIT
 URL:            https://github.com/ocamllabs/ocaml-ctypes/
@@ -26,17 +26,17 @@
 make

 %install
-export DESTDIR=$RPM_BUILD_ROOT
-export OCAMLFIND_DESTDIR=$RPM_BUILD_ROOT%{_libdir}/ocaml
-export OCAMLFIND_LDCONF=ignore
-rm -rf %{buildroot}
-mkdir -p %{buildroot}/%{_libdir}/ocaml
-export OCAMLFIND_DESTDIR=%{buildroot}/%{_libdir}/ocaml
+export OCAMLFIND_DESTDIR=%{buildroot}%{_libdir}/ocaml
+mkdir -p $OCAMLFIND_DESTDIR/stublibs
 make install

 %files
 %doc README.md LICENSE CHANGES.md
 %{_libdir}/ocaml/ctypes
+%{_libdir}/ocaml/stublibs/dllctypes_stubs.so
+%{_libdir}/ocaml/stublibs/dllctypes_stubs.so.owner
+%{_libdir}/ocaml/stublibs/dllctypes-foreign-base_stubs.so
+%{_libdir}/ocaml/stublibs/dllctypes-foreign-base_stubs.so.owner
 %exclude %{_libdir}/ocaml/ctypes/*.a
 %exclude %{_libdir}/ocaml/ctypes/*.cmxa
 %exclude %{_libdir}/ocaml/ctypes/*.cmx
@@ -49,6 +49,9 @@
 %{_libdir}/ocaml/ctypes/*.mli

 %changelog
+* Fri May  1 2015 Si Beaumont <simon.beaumont@citrix.com> - 0.4.1-2
+- Package shared libaries in the right place
+
 * Thu Apr 16 2015 Jon Ludlam <jonathan.ludlam@citrix.com> - 0.4.1-1
 - New upstream release
```

**Comment by djs55** [comment]
Thanks, I'll speculatively close this and let you know if it recurs!
